name: Azure Static Web Apps CI/CD - Flutter

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Flutter Web
    steps:
      - uses: actions/checkout@v4  # Checkout source code

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      # Install dependencies and build
      - run: flutter pub get
      - run: flutter build web --release

      # Deploy to Azure Static Web Apps
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Needed for PRs
          action: "upload"
          app_location: "/"
          output_location: "build/web"
          api_location: ""
          app_build_command: "flutter build web" # No backend API

# No need for a separate cleanup job — Azure handles PR preview cleanup automatically on PR close
